- hosts: all
  vars:
    - download: "{{ lookup('ENV', 'HOME') }}/fabric-samples"
  tasks:
    - name: download sample structure from github
      git:
       repo: https://github.com/nakao4532/fabric-samples.git
       dest: "{{ download }}"
       version: master
